// Database Statis Daftar Siswa XII Angkatan 2026/2027
export const DATA_SISWA = {

    "XII DPIB 1": ["ABI DWI ARYANSYAH", "ADRIAN JULY SAPUTRA", "AGNES FIDELA ASMARA", "AHMAD FAQIH HUNTELAAR", "AININ DINIYA HAQQI", "ALVIN ANDRY PRATAMA", "ANGGIA FAULINA", "AZZAHRA KAYLA NURANISA", "BAGUS TRI PUJIANTO", "CELVIN NIKO PRATAMA", "DANI FIRMANSYAH", "DIKA PRATAMA", "FAJAR DZULKARNAEN", "GEVHANDRA MILANDO", "HENDRA KURNIAWAN", "INTAN BARO MAHARANI", "KEYSIA PUTRI HANDAYANI", "MARCEL ADITYA", "MUHAMAD FAREL RADITYA", "MUHAMMAD AGIL SAPUTRA", "MUHAMMAD ASFA ALDIKA", "MUHAMMAD HAFFIYAN ZASIN", "NINGRUM NUR ANNISA", "RAFFI GALIH PRASETYO", "RAKA RESKIADITIA HALTARA", "RIO ZET MIKO", "SYAMSUL ANWAR ARAFI"],
    "XII DPIB 2": ["ADZKIA PURNOMO", "AFDAL NUR ROHIM", "AISYA AZZAHRA SINTIA", "ANDI SETIAWAN", "ARBA FIRMANSYAH", "ARDA JEPRIYAN SYACH", "AZIZ MAULANA ISHAK", "DIKKY DWI WIBOWO", "FADLI AZKA RAMANDIKA", "FAHRIZA RISWANDI", "FAREL PUTRA RAMADHAN", "GILANG SETIA AN", "INKA NABILA", "INNA RAFFA FIRIZKU SUBING", "IRWAN SAPUTRA", "MUHAMMAD IQBAL MAULANA", "MUHAMMAD NANDA ARYA REZA", "MUHAMMAD SYAHRUL MUNIR", "MUHAMMAD TAUFIQUZZIYAD", "NAIFA MEZZALUNA RAMADHANI", "NOVAL KHOIRUL EFENDI", "PANDU ADJIE DINATA", "QOIS NUR RAHMAN", "RAMA YOGA PRATAMA", "REFI ARTIKASARI", "RISKA RAHMAWARDANI", "RIZKY ADITYA", "RIZKY PRATAMA", "SITI RAHMAWATI", "SULTAN PASHA ALTAFA", "TIRTA NUR KHOIRUDIN", "VENY FERAWATI", "YUSUF RAMA WINATA", "ZHULFA ANISA RAYIKINANTI"],
    "XII TKP" : [
        "ABDUL SAPENDI", "ADITYA PRATAMA", "AHMAD ZAENURI", "ALDI PRATAMA", "ANDES HANAPI", 
        "ANDRA AHMAD MUSTAKIM", "ANGGA SAPUTRA", "ARUNG AKBAR ADIWANGSA", "AWAN FAUSTA", "BAYU RIDO AGUNG ALI", 
        "DIMAS MAULANA HERLAMBANG", "DINO ARDIANSYAH", "FAHRIZAL EKA WIJAYA", "FELIKS KRISDIANTORO", "GUSTI PRASETYO", 
        "IBNU CHOIRUL FIQRIANSYAH", "JESIKA ADITYA RAMADHANI", "JIBRIL ABBAS", "MUHAMAD ALI MAKSUN", "MUHAMMAD DZULFIQAR TAJJUDIN", 
        "MUHAMMAD RIZKY ADYTIA", "MUSTAFA WIRATAMA SAMPURNA JA", "RAHIL SAPUTRA", "REDI PERNANDA", "RINA SAFIRA FEBRIANA", 
        "RIZKI ALVIANSYAH", "SATRIA RAMADHAN", "SELO AL FATAH", "SUGI NAINGGOLAN", "WULANDARI", 
        "M. AL FAHRI"]
};